export enum ActionKeys {
  ALERT = 'ALERT',
  CLEAR_ALERTS = 'CLEAR_ALERTS',
  CLEAR_ALERT = 'CLEAR_ALERT',

  LOADED_HOST_MAP = 'LOADED_HOST_MAP',
  APP_LOADING = 'APP_LOADING',
  APP_NOT_LOADING = 'APP_NOT_LOADING',
  AUTHENTICATED = 'AUTHENTICATED',
  LOGOUT = 'LOGOUT',

  TIMELINE_ITEM_ADDED = 'TIMELINE_ITEM_ADDED',
  TIMELINE_ITEM_UPDATED = 'TIMELINE_ITEM_UPDATED',

  USER_FETCHED = 'USER_FETCHED',
  PATIENT_ADDED = 'PATIENT_ADDED',
  INVITATION_LOADING = 'INVITATION_LOADING',
  INVITATION_FINISHED = 'INVITATION_FINISHED',

  CHANGE_USER_TO_ADMIN = 'CHANGE_USER_TO_ADMIN',
  CHANGE_USER_TO_DOCTOR = 'CHANGE_USER_TO_DOCTOR',
  CHANGE_USER_TO_PATIENT = 'CHANGE_USER_TO_PATIENT',

  TOGGLE_GUTTER_NAV = 'TOGGLE_GUTTER_NAV',

  SET_ACTIVE_USER = 'SET_ACTIVE_USER',

  NOTIFICATIONS_FETCHED = 'NOTIFICATIONS_FETCHED',
}
